name: "Choreo Deployer"
description: "Deploy newly built docker images to kubernetes through the Choreo API"
author: WSO2
branding:
  icon: "arrow-up-circle"
  color: "orange"
inputs:
  domain:
    description: "Choreo API Domain."
    required: false
    default: ""
  org-id:
    description: "Organization ID"
    required: true
    default: "0"
  project-id:
    description: "Project ID"
    required: true
    default: ""
  app-id:
    description: "App ID"
    required: true
    default: ""
  env-id:
    description: "Environment ID"
    required: true
    default: ""
  version:
    description: "Version ID"
    required: true
    default: ""
  branch:
    description: "Branch"
    required: false
    default: :"main"
  image-name: 
    description: "Name of the image"
    required: true
    default: ""
  git-hash-date:
    description: "Date of the built tag"
    required: false
    default: ""
  git-hash: 
    description: "Name of the built tag"
    required: true
    default: 'latest'
  gitops-hash: 
    description: 'Name of the built tag of gitops repo'
    required: true
    default: "latest"
  token: 
    description: 'Secret token for validation'
    required: true
    default: ""
  port-extract-file-path: 
    description: "Deploymnet yaml file path to extract ports"
    required: true
    default: "target/kubernetes/workspace/workspace.yaml"
  debug: 
    description: "Enable request debug"
    required: false
    default: "false"
  is-http-based: 
    description: "Status of the http based app"
    required: false
    default: ""
  container-id: 
    description: "Container Id"
    required: false
    default: "N/A"
  is-container-deployment: 
    description: "Check container deployment"
    required: false
    default: ""
  oas-file-path: 
    description: "Oas file path"
    required: false
    default: ""
  is-auto-deploy: 
    description: "Service auto deploy status"
    required: false
    default: "false"
  run-id:
    description: "Run ID of the current build"
    required: false
    default: ""
  organizationUuid:
    description: 'Organization UUID'
    required: true
    default: ''
  component-sub-type:
    description: "Component sub type detected at build time (e.g. 'webhook'), used to promote event handler components to their service type"
    required: false
    default: ""
outputs:
  choreo-status:
    description: "Status of the Webhook Call to choreo"
runs:
  using: "node16"
  main: "dist/index.js"
